# Generated by Django 5.0.6 on 2024-07-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getapps', '0002_delete_application_delete_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='onemoment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='onemoment_images/', verbose_name='Image'),
        ),
    ]
